#
# Makefile for the  DVB-S/S2 driver.
#

obj-$(CONFIG_AM_DVB) += avl.o


obj-$(CONFIG_AM_DVB) += r848.o aml_fe.o

EXTRA_CFLAGS += -I.
EXTRA_CFLAGS += -Idrivers/media/dvb-core -Idrivers/media/usb/dvb-usb -Idrivers/media/dvb-frontends -Idrivers/media/tuners

