#!/bin/sh
################################################################################
#      This file is part of Alex@ELEC - http://www.alexelec.in.ua
#      Copyright (C) 2011-2017 Alexandr Zuyev (alex@alexelec.in.ua)
################################################################################

SOURCEREMOTECONF="/tmp/remote/remote.conf"
TARGETREMOTECONF="/storage/.config/amremote/remote.conf"
REMOTECONFPRESENT="no"

mkdir -p /tmp/remote
mkdir -p /tmp/system
mount -o ro /dev/system /tmp/system

if [ -f /tmp/system/etc/remote.conf ] ; then
  cp -f /tmp/system/etc/remote.conf $SOURCEREMOTECONF
  REMOTECONFPRESENT="yes"
elif [ -f /tmp/system/remote.conf ] ; then
  cp -f /tmp/system/remote.conf $SOURCEREMOTECONF
  REMOTECONFPRESENT="yes"
fi

umount /tmp/system

if [ "$REMOTECONFPRESENT" = "yes" ]; then
  cp -f "$SOURCEREMOTECONF" "$TARGETREMOTECONF"
    sed -i 's/ 15[^0-9]*$/ 1/
            s/ 63[^0-9]*$/ 90/
            s/ 97[^0-9]*$/ 28/
            s/ 102[^0-9]*$/ 172/
            s/ 125[^0-9]*$/ 46/
            s/ 142[^0-9]*$/ 116/
            s/ 143[^0-9]*$/ 116/
            s/ 158[^0-9]*$/ 1/
            s/ 183[^0-9]*$/ 59/
            s/ 184[^0-9]*$/ 399/
            s/ 185[^0-9]*$/ 400/
            s/ 186[^0-9]*$/ 60/
            s/ 232[^0-9]*$/ 38/
            s/ 240[^0-9]*$/ 164/
            s/ 241[^0-9]*$/ 163/
            s/ 242[^0-9]*$/ 165/
            s/ 244[^0-9]*$/ 208/
            s/ 245[^0-9]*$/ 168/
            s/ 264[^0-9]*$/ 63/
            s/ 704[^0-9]*$/ 116/' "$TARGETREMOTECONF"

  /usr/bin/remotecfg "$TARGETREMOTECONF"
fi
