#!/bin/sh
################################################################################
#      This file is part of Alex@ELEC - http://www.alexelec.in.ua
#      Copyright (C) 2011-2017 Alexandr Zuyev (alex@alexelec.in.ua)
################################################################################

IMAGE_KERNEL="/flash/kernel.img"
IMAGE_SYSTEM="/flash/SYSTEM"

install_to_nand() {
  if [ -f $IMAGE_KERNEL -a -f $IMAGE_SYSTEM ] ; then
    if grep -q /dev/system /proc/mounts ; then
      echo "Unmounting SYSTEM partiton."
      umount -f /dev/system
    fi
    if systemctl is-active storage-nand.mount &>/dev/null ; then
      echo "Unmounting DATA partiton."
      systemctl stop storage-nand.mount
    fi
    mkdir -p /tmp/system

    mount -o rw,remount /flash

    echo -n "Writing kernel image..."
    dd if="$IMAGE_KERNEL" of="/dev/boot" bs=64K status=none && sync
    echo "done."

    echo -n "Formatting SYSTEM partition..."
    mke2fs -F -q -t ext4 -m 0 /dev/system > /dev/null
    e2fsck -n /dev/system &> /dev/null
    echo "done."

    echo -n "Copying SYSTEM files..."
    mount -o rw /dev/system /tmp/system
    cp $IMAGE_SYSTEM /tmp/system && sync
    umount /tmp/system
    echo "done."

    echo -n "Formatting DATA partition..."
    mke2fs -F -q -t ext4 -m 0 /dev/data > /dev/null
    e2fsck -n /dev/data &> /dev/null
    echo "done."

    echo "All done! Rebooting in 5s..."
    sleep 5
    nand-reboot

  else
    echo "No AlexELEC image found on /flash! Exiting..."
  fi
}

echo "This script will erase BOOT, SYSTEM, and DATA on your device"
echo "and install AlexELEC that you booted from SD card/USB drive."
echo ""
echo "The script does not have any safeguards!"
echo ""
read -p "Type \"yes\" if you know what you are doing or anything else to exit: " choice
case "$choice" in
  yes) install_to_nand ;;
esac
