#!/bin/sh
################################################################################
#      This file is part of Alex@ELEC - http://www.alexelec.in.ua
#      Copyright (C) 2011-2017 Alexandr Zuyev (alex@alexelec.in.ua)
################################################################################

if [ -z "$1" ]; then
  BRANCH="krypton"
else
  BRANCH=$1
fi

echo "BRANCH=$BRANCH getting sources..."
  if [ ! -d kodi-language-addons.git ]; then
    git clone --depth=1 -b $BRANCH https://github.com/xbmc/repo-resources.git kodi-language-addons.git
  fi

  cd kodi-language-addons.git
    git pull
    GIT_REV=`git log -n1 --format=%h`
  cd ..

echo "copying sources..."
  rm -rf kodi-language-addons-$GIT_REV
  cp -R kodi-language-addons.git kodi-language-addons-$GIT_REV

echo "cleaning sources..."
  cd kodi-language-addons-$GIT_REV
    rm -rf .git*
    ls | grep -v resource.language | xargs rm -r
  cd ..

echo "packing sources..."
  tar cvJf kodi-language-addons-$GIT_REV.tar.xz kodi-language-addons-$GIT_REV

echo "remove temporary sourcedir..."
  rm -rf kodi-language-addons.git
  rm -rf kodi-language-addons-$GIT_REV
