#!/bin/sh
################################################################################
#      This file is part of Alex@ELEC - http://www.alexelec.in.ua
#      Copyright (C) 2011-2017 Alexandr Zuyev (alex@alexelec.in.ua)
################################################################################

# choose "LATEST" or a date like "2016-03-29-d3f519301944" for the driver package
# chose from here http://linuxtv.org/downloads/drivers/
MEDIA_BUILD_VERSION="LATEST"

echo "getting sources..."
  if [ ! -d media_build.git ]; then
    git clone git://linuxtv.org/media_build.git media_build.git
  fi

  cd media_build.git
    git pull
    GIT_REV=`git log -n1 --format=%h`

    sed -i -e "/^LATEST_TAR/s/-LATEST/-$MEDIA_BUILD_VERSION/g" linux/Makefile
    make -C linux/ download
    make -C linux/ untar
  cd ..

echo "copying sources..."
  rm -rf media_build-$GIT_REV
  cp -R media_build.git media_build-$GIT_REV

echo "cleaning sources..."
  rm -rf media_build-$GIT_REV/.git

echo "packing sources..."
  tar cvJf media_build-$GIT_REV.tar.xz media_build-$GIT_REV

echo "remove temporary sourcedir..."
  rm -rf media_build-$GIT_REV
  rm -rf media_build.git
