#!/bin/sh
################################################################################
#      This file is part of Alex@ELEC - http://www.alexelec.in.ua
#      Copyright (C) 2011-2017 Alexandr Zuyev (alex@alexelec.in.ua)
################################################################################

IMAGE_KERNEL="/flash/kernel.img"
IMAGE_SYSTEM="/flash/SYSTEM"
IMAGE_DTB="/flash/dtb.img"
IMAGE_LOGO="/usr/share/bootloader/logo.img"
BACKUP_DATE=$(date +%Y%m%d%H%M%S)

install_to_nand() {
  if [ -f $IMAGE_KERNEL -a -f $IMAGE_SYSTEM ] ; then
    fw_setenv upgrade_step 2

    if grep -q /dev/system /proc/mounts ; then
      echo "Unmounting SYSTEM partiton."
      umount -f /dev/system
    fi
    if systemctl is-active storage-nand.mount &>/dev/null ; then
      echo "Unmounting DATA partiton."
      systemctl stop storage-nand.mount
    fi
    mkdir -p /tmp/system

    mount -o rw,remount /flash

    read -p "Backup NAND to SD card? [Y/n] " choice
    case "$choice" in
      [nN]*)
        ;;
      *)
        if [ -e /dev/dtb ] ; then
          echo -n "Backing up device tree..."
          dd if="/dev/dtb" of="/flash/dtb-$BACKUP_DATE.img" status=none && sync
          echo "done."
        fi

        if [ -e /dev/recovery ] ; then
          echo -n "Backing up recovery partition..."
          dd if="/dev/recovery" of="/flash/recovery-$BACKUP_DATE.img" bs=64K status=none && sync
          echo "done."
        fi

        if [ -e /dev/logo -a -e $IMAGE_LOGO ] ; then
          echo -n "Backing up logo partition..."
          dd if="/dev/logo" of="/flash/logo-$BACKUP_DATE.img" status=none && sync
          echo "done."
        fi
        ;;
    esac

    echo -n "Writing kernel image..."
    dd if="$IMAGE_KERNEL" of="/dev/boot" bs=64K status=none && sync
    echo "done."

    echo -n "Formatting SYSTEM partition..."
    mke2fs -F -q -t ext4 -m 0 /dev/system > /dev/null
    e2fsck -n /dev/system &> /dev/null
    echo "done."

    echo -n "Copying SYSTEM files..."
    mount -o rw /dev/system /tmp/system
    cp $IMAGE_SYSTEM /tmp/system && sync
    umount /tmp/system
    echo "done."

    if [ -f $IMAGE_DTB ] ; then
      echo -n "Writing device tree image..."
      dd if="$IMAGE_DTB" of="/dev/dtb" bs=262144 status=none && sync
      echo "done."
    fi

    if [ -f $IMAGE_LOGO ] ; then
      echo -n "Writing logo image..."
      dd if="$IMAGE_LOGO" of="/dev/logo" status=none && sync
      echo "done."
    fi

    echo -n "Formatting DATA partition..."
    mke2fs -F -q -t ext4 -m 0 /dev/data > /dev/null
    e2fsck -n /dev/data &> /dev/null
    echo "done."

    read -p "Do you want to copy your user data to internal data partition? [Y/n] " choice
    case "$choice" in
      [nN]*)
        ;;
      *)
        echo -n "Stopping Kodi..."
        systemctl stop kodi
        echo "done."
        echo "Copying user data..."
        mkdir -p /tmp/data
        mount -o rw /dev/data /tmp/data
        cp -av /storage/. /tmp/data/
        echo -n "Restarting Kodi..."
        systemctl start kodi
        echo "done."
        ;;
    esac

    echo "All done! You can now continue using your AlexELEC system or type \"nand-reboot\" to reboot from internal memory."
    echo "WARNING: If your internal memory layout is different from standard Amlogic, you have to reboot and perform this operation again!"

  else
    echo "No AlexELEC image found on /flash! Exiting..."
  fi
}

echo "This script will erase BOOT, SYSTEM, DATA and DTB on your device"
echo "and install AlexELEC that you booted from SD card/USB drive."
echo ""
echo "It will create a backup of device tree and recovery partition on your boot media."
echo ""
echo "The script does not have any safeguards!"
echo ""
read -p "Type \"yes\" if you know what you are doing or anything else to exit: " choice
case "$choice" in
  yes) install_to_nand ;;
esac
