#!/bin/bash
################################################################################
#      This file is part of Alex@ELEC - http://www.alexelec.in.ua
#      Copyright (C) 2011-2017 Alexandr Zuyev (alex@alexelec.in.ua)
################################################################################

. config/options $1

clean_package() {
  printf "%${BUILD_INDENT}c ${boldred}CLEAN${endcolor}    $1\n" ' '>&$SILENT_OUT
  export BUILD_INDENT=$((${BUILD_INDENT:-1}+$BUILD_INDENT_SIZE))

  if [ "$CLEAN_SOURCES" = true ]; then
    rm -rf $SOURCES/$1
    return
  fi

  for i in $BUILD/$1-*; do
    if [ -d $i -a -f "$i/.alexelec-unpack" ] ; then
      . "$i/.alexelec-unpack"
      if [ "$STAMP_PKG_NAME" = "$1" ]; then
        printf "%${BUILD_INDENT}c ${boldred}*${endcolor} ${red}Removing $i ...${endcolor}\n" ' '>&$SILENT_OUT
        rm -rf $i
      fi
    else
      # force clean if no stamp found (previous unpack failed)
      printf "%${BUILD_INDENT}c * Removing $i ...\n" ' '>&$SILENT_OUT
      rm -rf $i
    fi
  done
  rm -f $STAMPS/$1/build_*
}

if [ "$1" = "--all" ]; then
  if [ ! -z "$2" ]; then
    for PROJECT in $(ls -1 projects); do
      for archfile in projects/$PROJECT/linux/linux.*.conf; do
        if [ ! -f "$archfile" ]; then
          archfile="$(ls -1 projects/$PROJECT/linux/*/linux.*.conf | head -1)"
        fi
        ARCH=`echo $archfile | sed -n '$s/\.conf//;$s/.*\.//p'`
        PROJECT=$PROJECT ARCH=$ARCH ./scripts/clean $2
      done
    done
  fi
else
  if [ ! -z "$1" ]; then
    clean_package $1
  fi
fi

