#!/bin/bash
################################################################################
#      This file is part of Alex@ELEC - http://www.alexelec.in.ua
#      Copyright (C) 2011-2017 Alexandr Zuyev (alex@alexelec.in.ua)
################################################################################

. config/options $1

if [ -z "$3" ]; then
  echo "usage: $0 package_name file_pattern target_dir"
  exit 1
fi

[ -z "$PKG_URL" -o -z "$PKG_SOURCE_NAME" ] && exit 1
[ ! -d "$SOURCES/$1" -o ! -d "$3" ] && exit 1

case $PKG_SOURCE_NAME in
  $2)
    f="$SOURCES/$1/$PKG_SOURCE_NAME"
    if [ ! -f $f ]; then
      echo "error: File $PKG_SOURCE_NAME doesn't exists in package $1 sources directory"
      echo "have you called scripts/extract before scripts/get ?"
      exit 1
    fi
    case $PKG_SOURCE_NAME in
      *.tar)
        tar xf $f -C $3
        ;;
      *.tar.bz2 | *.tbz)
        tar xjf $f -C $3
        ;;
      *.tar.gz | *.tgz)
        tar xzf $f -C $3
        ;;
      *.tar.xz | *.txz)
        tar xJf $f -C $3
        ;;
      *.7z)
        mkdir -p $3/$1
        7z x -o$3/$1 $f
        ;;
      *.zip)
        unzip -q $f -d $3
        ;;
      *.diff | *.patch)
        cat $f | patch -d $3 -p1
        ;;
      *.diff.bz2 | *.patch.bz2 | patch-*.bz2)
        bzcat $f | patch -d $3 -p1
        ;;
      *.diff.gz | *.patch.gz | patch-*.gz)
        zcat $f | patch -d $3 -p1
        ;;
      *)
        cp -pPR $f $3
        ;;
    esac
    ;;
esac
